<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="ja" sourcelanguage="en">
  <context>
    <name>@default</name>
    <message>
      <source>HYBRID_ADV_ARGS</source>
      <translation>上級者</translation>
    </message>
    <message>
      <source>HYBRID_HYPOTHESIS</source>
      <translation>ハイブリッド</translation>
    </message>
    <message>
      <source>HYBRID_OPTIMIZATION_LEVEL</source>
      <translation>最適化レベル</translation>
    </message>
    <message>
      <source>HYBRID_PERMISSION_DENIED</source>
      <translation>作業ディレクトリに書き込み権限がありません</translation>
    </message>
    <message>
      <source>HYBRID_STD_ARGS</source>
      <translation>パラメータ</translation>
    </message>
    <message>
      <source>HYBRID_TITLE</source>
      <translation>Hypothesisの構築</translation>
    </message>
    <message>
      <source>HYBRID_BOUNDARY_LAYERS_GROWTH</source>
      <translation>境界層成長度</translation>
    </message>
    <message>
      <source>HYBRID_BOUNDARY_LAYERS_HELP</source>
      <translation>Pay attention:
due to random conventions of normals orientations of many mesher,
downward means inward and upward means outward ...
... or vice versa.
警告: 多くのメッシュの法線方向が不揃いのため、下向きが内側、上向きが外側、またはその逆になっています。</translation>
    </message>
    <message>
      <source>HYBRID_LAYER_GROWTH_INWARD</source>
      <translation>内側へ成長</translation>
    </message>
    <message>
      <source>HYBRID_LAYER_GROWTH_OUTWARD</source>
      <translation>外側へ成長</translation>
    </message>
    <message>
      <source>HYBRID_LAYER_GROWTH_UPWARD</source>
      <translation>上側へ成長</translation>
    </message>
    <message>
      <source>HYBRID_LAYER_GROWTH_DOWNWARD</source>
      <translation>下側へ成長</translation>
    </message>
    <message>
      <source>HYBRID_GENERATION_ELEMENT</source>
      <translation>残りボリューム内にあるメッシュの要素タイプ</translation>
    </message>
    <message>
      <source>HYBRID_GENERATION_TETRA_DOMINANT</source>
      <translation>主に四面体</translation>
    </message>
    <message>
      <source>HYBRID_GENERATION_HEXA_DOMINANT</source>
      <translation>主に六面体</translation>
    </message>
    <message>
      <source>HYBRID_ADD_MULTINORMALS</source>
      <translation>開いたリッジと角に別の法線を追加</translation>
    </message>
    <message>
      <source>HYBRID_MULTINORMAL_ANGLE</source>
      <translation>複数法線角の追加</translation>
    </message>
    <message>
      <source>HYBRID_SMOOTH_NORMALS</source>
      <translation>閉じたリッジと角の法線を平滑化</translation>
    </message>
    <message>
      <source>HYBRID_HeightFirstLayer</source>
      <translation>初期レイヤーの高さ</translation>
    </message>
    <message>
      <source>HYBRID_NbOfBoundaryLayers</source>
      <translation>境界層の数</translation>
    </message>
    <message>
      <source>HYBRID_BoundaryLayersProgression</source>
      <translation>境界層の等比数列</translation>
    </message>
    <message>
      <source>HYBRID_TO_MESH_HOLES</source>
      <translation>メッシュの穴</translation>
    </message>
    <message>
      <source>HYBRID_LAYERS_ON_ALL_WRAP</source>
      <translation>すべてのラップ上のメッシュ層</translation>
    </message>
    <message>
      <source>HYBRID_TO_MAKE_DOMAIN_GROUPS</source>
      <translation>ドメインのグループ作成</translation>
    </message>
    <message>
      <source>ADVANCED_MESHING_GROUP_TITLE</source>
      <translation>上級者メッシュオプション</translation>
    </message>
    <message>
      <source>INIT_MEMORY_SIZE</source>
      <translation>初期メモリサイズ</translation>
    </message>
    <message>
      <source>KEEP_WORKING_FILES</source>
      <translation>すべての作業ファイルを維持</translation>
    </message>
    <message>
      <source>COLLISION_MODE</source>
      <translation>レイヤー間の干渉時の振る舞い</translation>
    </message>
    <message>
      <source>COLLISION_DECREASE</source>
      <translation>層高さを減少</translation>
    </message>
    <message>
      <source>COLLISION_STOP</source>
      <translation>局所層数の削減</translation>
    </message>
    <message>
      <source>LEVEL_NONE</source>
      <translation>なし</translation>
    </message>
    <message>
      <source>LEVEL_LIGHT</source>
      <translation>細線</translation>
    </message>
    <message>
      <source>LEVEL_MEDIUM</source>
      <translation>中間（標準）</translation>
    </message>
    <message>
      <source>LEVEL_STANDARDPLUS</source>
      <translation>標準＋</translation>
    </message>
    <message>
      <source>LEVEL_STRONG</source>
      <translation>太線</translation>
    </message>
    <message>
      <source>LOG_IN_FILE</source>
      <translation>ファイル内のログを印刷</translation>
    </message>
    <message>
      <source>LOG_GROUP_TITLE</source>
      <translation>ログとデバッグ</translation>
    </message>
    <message>
      <source>MAX_MEMORY_SIZE</source>
      <translation>最大メモリサイズ</translation>
    </message>
    <message>
      <source>MEGABYTE</source>
      <translation>MB</translation>
    </message>
    <message>
      <source>MEMORY_GROUP_TITLE</source>
      <translation>メモリ設定</translation>
    </message>
    <message>
      <source>NO_INITIAL_CENTRAL_POINT</source>
      <translation>最初の中間点を削除</translation>
    </message>
    <message>
      <source>RECOVERY_VERSION</source>
      <translation>境界復元バージョンの使用</translation>
    </message>
    <message>
      <source>FEM_CORRECTION</source>
      <translation>FEM修正を使用</translation>
    </message>
    <message>
      <source>HYBRID_GRADATION</source>
      <translation>ボリュームグラデーション</translation>
    </message>
    <message>
      <source>REMOVE_LOG_ON_SUCCESS</source>
      <translation>成功したログをを削除</translation>
    </message>
    <message>
      <source>SELECT_DIR</source>
      <translation>...</translation>
    </message>
    <message>
      <source>TEXT_OPTION</source>
      <translation>テキストオプション</translation>
    </message>
    <message>
      <source>TO_ADD_NODES</source>
      <translation>新規節点の作成</translation>
    </message>
    <message>
      <source>VERBOSE_LEVEL</source>
      <translation>詳細レベル</translation>
    </message>
    <message>
      <source>WORKING_DIR</source>
      <translation>作業ディレクトリ</translation>
    </message>
    <message>
      <source>HYBRID_ENFORCED_VERTICES</source>
      <translation>強制頂点</translation>
    </message>
    <message>
      <source>HYBRID_ENFORCED_MESHES</source>
      <translation>レイヤメッシュ</translation>
    </message>
    <message>
      <source>HYBRID_ENF_NAME_COLUMN</source>
      <translation>名前</translation>
    </message>
    <message>
      <source>HYBRID_ENF_VER_X_COLUMN</source>
      <translation>X</translation>
    </message>
    <message>
      <source>HYBRID_ENF_VER_Y_COLUMN</source>
      <translation>Y</translation>
    </message>
    <message>
      <source>HYBRID_ENF_VER_Z_COLUMN</source>
      <translation>Z</translation>
    </message>
    <message>
      <source>HYBRID_ENF_SIZE_COLUMN</source>
      <translation>サイズ</translation>
    </message>
    <message>
      <source>HYBRID_ENF_ENTRY_COLUMN</source>
      <translation>頂点の登録</translation>
    </message>
    <message>
      <source>HYBRID_ENF_MESH_CONSTRAINT_COLUMN</source>
      <translation>拘束</translation>
    </message>
    <message>
      <source>HYBRID_ENF_VER_COMPOUND_COLUMN</source>
      <translation>混合</translation>
    </message>
    <message>
      <source>HYBRID_ENF_GROUP_COLUMN</source>
      <translation>グループ</translation>
    </message>
    <message>
      <source>HYBRID_ENF_SELECT_VERTEX</source>
      <translation>頂点の選択</translation>
    </message>
    <message>
      <source>HYBRID_ENF_SELECT_MESH</source>
      <translation>メッシュの選択</translation>
    </message>
    <message>
      <source>HYBRID_ENF_VER_X_LABEL</source>
      <translation>X:</translation>
    </message>
    <message>
      <source>HYBRID_ENF_VER_Y_LABEL</source>
      <translation>Y:</translation>
    </message>
    <message>
      <source>HYBRID_ENF_VER_Z_LABEL</source>
      <translation>Z:</translation>
    </message>
    <message>
      <source>HYBRID_ENF_MESH_CONSTRAINT_LABEL</source>
      <translation>拘束:</translation>
    </message>
    <message>
      <source>HYBRID_ENF_MESH_CONSTRAINT_NODE</source>
      <translation>節点</translation>
    </message>
    <message>
      <source>HYBRID_ENF_MESH_CONSTRAINT_EDGE</source>
      <translation>エッジ</translation>
    </message>
    <message>
      <source>HYBRID_ENF_MESH_CONSTRAINT_FACE</source>
      <translation>面</translation>
    </message>
    <message>
      <source>HYBRID_ENF_SIZE_LABEL</source>
      <translation>サイズ:</translation>
    </message>
    <message>
      <source>HYBRID_ENF_GROUP_LABEL</source>
      <translation>グループ:</translation>
    </message>
    <message>
      <source>HYBRID_ENF_ADD</source>
      <translation>追加</translation>
    </message>
    <message>
      <source>HYBRID_ENF_REMOVE</source>
      <translation>削除</translation>
    </message>
    <message>
      <source>HYBRID_ENF_VER_INFO</source>
      <translation>&lt;b&gt;警告&lt;/b&gt;: 強制頂点は現在 w/o がジオメトリに関連付けたメッシュの説明を考慮のみしています。</translation>
    </message>
    <message>
      <source>HYBRID_ENF_MESH_INFO</source>
      <translation>&lt;b&gt;警告&lt;/b&gt;: 強制メッシュは現在 w/o がジオメトリに関連付けたメッシュの説明を考慮のみしています。</translation>
    </message>
  </context>
</TS>
